name: my-env
channels:
  - conda-forge
  - defaults
dependencies:
  - earthengine-api=0.1.231
  - pip=20.2.2
  - poppler=0.65.0
  - poppler-data=0.4.9
  - postgresql=11.2
  - proj=6.2.1
  - pydrive=1.3.1
  - pyproj=2.6.1.post1
  - python=3.7.7
  - requests=2.24.0

  - pip:
    - docker-compose==1.26.2
    - geojson==2.5.0
    - pytest==6.0.1
    - python-dotenv==0.14.0
    - responses==0.11.0
