name: CI

on:
    push:
      branches: [ master ]
    pull_request:
      branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest
    strategy:
      matrix:
        python-version: [3.7]

    env:
      COMPOSE_FILE: docker/docker-compose.yml
      PYTHON_VERSION: ${{ matrix.python-version }}

    steps:
    - uses: actions/checkout@v2

    - uses: goanpeca/setup-miniconda@v1
      with:
        auto-update-conda: true
        python-version: ${{ matrix.python-version }}
        activate-environment: my-env
        environment-file: environment-3.7.yml
        channels: conda-forge
  
    - name: Copy env_file as env
      shell: bash -l {0}
      run: |
        cp env_sample .env

    - name: Install dependencies
      shell: bash -l {0}
      run: |
        make install

    - name: Print key secrets
      shell: bash -l {0}
      env:
        CLIENT_ACCOUNT_ID: ${{ secrets.CLIENT_ACCOUNT_ID }}
        CLIENTE_SECRET: ${{ secrets.CLIENTE_SECRETS }}
        CLIENTE_ID: ${{ secrets.CLIENTE_ID }}
        PROJETO_ID: ${{ secrets.PROJETO_ID }}
        ACESSO_TOKEN: ${{ secrets.ACESSO_TOKEN }}
        REFRESCA_TOKEN: ${{ secrets.REFRESCA_TOKEN }}
      run: |
        make print_key
        make configure_environ
        make list_dir
